In [11]:
from pythainlp.tokenize import word_tokenize

text = "เมื่อวันพฤหัสบดีที่ 31 ก.ค. 2568 โดนัลด์ ทรัมป์ ประธานาธิบดีสหรัฐฯ ประกาศผ่าน Truth Social ว่า เขาจะเลื่อนการบังคับใช้มาตรการภาษีต่างตอบแทนอัตรา 30% กับเม็กซิโกไปก่อน โดยจะใช้ข้อตกลงเดิมซึ่งจะเก็บภาษีสินค้าบางรายการที่นำเข้าจากเม็กซิโกในอัตรา 25% ต่อไปอีก 90 วัน ในระหว่างนั้นทั้งสองฝ่ายจะหาทางทำข้อตกลงการค้าร่วมกัน"
all_words = word_tokenize(text, engine="newmm") 
print(all_words)
print(len(all_words))

['เมื่อ', 'วัน', 'พฤหัสบดี', 'ที่', ' ', '31', ' ', 'ก.ค.', ' ', '2568', ' ', 'โดนัลด์', ' ', 'ทรัมป์', ' ', 'ประธานาธิบดี', 'สหรัฐฯ', ' ', 'ประกาศ', 'ผ่าน', ' ', 'Truth', ' ', 'Social', ' ', 'ว่า', ' ', 'เขา', 'จะ', 'เลื่อน', 'การบังคับใช้', 'มาตรการ', 'ภาษี', 'ต่าง', 'ตอบแทน', 'อัตรา', ' ', '30', '%', ' ', 'กับ', 'เม็กซิโก', 'ไป', 'ก่อน', ' ', 'โดย', 'จะ', 'ใช้', 'ข้อตกลง', 'เดิม', 'ซึ่ง', 'จะ', 'เก็บภาษี', 'สินค้า', 'บาง', 'รายการ', 'ที่', 'นำเข้า', 'จาก', 'เม็กซิโก', 'ใน', 'อัตรา', ' ', '25', '%', ' ', 'ต่อไป', 'อีก', ' ', '90', ' ', 'วัน', ' ', 'ในระหว่างนั้น', 'ทั้งสองฝ่าย', 'จะ', 'หาทาง', 'ทำ', 'ข้อตกลง', 'การค้า', 'ร่วมกัน']
81


In [12]:
vocab = {token:integer for integer,token in enumerate(all_words)}
vocab

{'เมื่อ': 0,
 'วัน': 71,
 'พฤหัสบดี': 2,
 'ที่': 56,
 ' ': 72,
 '31': 5,
 'ก.ค.': 7,
 '2568': 9,
 'โดนัลด์': 11,
 'ทรัมป์': 13,
 'ประธานาธิบดี': 15,
 'สหรัฐฯ': 16,
 'ประกาศ': 18,
 'ผ่าน': 19,
 'Truth': 21,
 'Social': 23,
 'ว่า': 25,
 'เขา': 27,
 'จะ': 75,
 'เลื่อน': 29,
 'การบังคับใช้': 30,
 'มาตรการ': 31,
 'ภาษี': 32,
 'ต่าง': 33,
 'ตอบแทน': 34,
 'อัตรา': 61,
 '30': 37,
 '%': 64,
 'กับ': 40,
 'เม็กซิโก': 59,
 'ไป': 42,
 'ก่อน': 43,
 'โดย': 45,
 'ใช้': 47,
 'ข้อตกลง': 78,
 'เดิม': 49,
 'ซึ่ง': 50,
 'เก็บภาษี': 52,
 'สินค้า': 53,
 'บาง': 54,
 'รายการ': 55,
 'นำเข้า': 57,
 'จาก': 58,
 'ใน': 60,
 '25': 63,
 'ต่อไป': 66,
 'อีก': 67,
 '90': 69,
 'ในระหว่างนั้น': 73,
 'ทั้งสองฝ่าย': 74,
 'หาทาง': 76,
 'ทำ': 77,
 'การค้า': 79,
 'ร่วมกัน': 80}

In [13]:
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

('เมื่อ', 0)
('วัน', 71)
('พฤหัสบดี', 2)
('ที่', 56)
(' ', 72)
('31', 5)
('ก.ค.', 7)
('2568', 9)
('โดนัลด์', 11)
('ทรัมป์', 13)
('ประธานาธิบดี', 15)
('สหรัฐฯ', 16)
('ประกาศ', 18)
('ผ่าน', 19)
('Truth', 21)
('Social', 23)
('ว่า', 25)
('เขา', 27)
('จะ', 75)
('เลื่อน', 29)
('การบังคับใช้', 30)
('มาตรการ', 31)
('ภาษี', 32)
('ต่าง', 33)
('ตอบแทน', 34)
('อัตรา', 61)
('30', 37)
('%', 64)
('กับ', 40)
('เม็กซิโก', 59)
('ไป', 42)
('ก่อน', 43)
('โดย', 45)
('ใช้', 47)
('ข้อตกลง', 78)
('เดิม', 49)
('ซึ่ง', 50)
('เก็บภาษี', 52)
('สินค้า', 53)
('บาง', 54)
('รายการ', 55)
('นำเข้า', 57)
('จาก', 58)
('ใน', 60)
('25', 63)
('ต่อไป', 66)
('อีก', 67)
('90', 69)
('ในระหว่างนั้น', 73)
('ทั้งสองฝ่าย', 74)
('หาทาง', 76)


In [14]:
import re
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}
    
    def encode(self, text):
        preprocessed = word_tokenize(text, engine="newmm") 
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
        
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        return text

In [15]:
tokenizer = SimpleTokenizerV1(vocab)

text = """เขาจะเลื่อนการบังคับใช้มาตรการภาษีต่างตอบแทนอัตรา"""
ids = tokenizer.encode(text)
print(ids)

[27, 75, 29, 30, 31, 32, 33, 34, 61]


In [16]:
tokenizer.decode(ids)

'เขา จะ เลื่อน การบังคับใช้ มาตรการ ภาษี ต่าง ตอบแทน อัตรา'

Adding special context tokens

In [17]:
tokenizer = SimpleTokenizerV1(vocab)

text = "เขาจะเลื่อนการบังคับใช้มาตรการ-- ภาษีต่างตอบแทนอัตรา"

tokenizer.encode(text)

KeyError: '--'

In [18]:
all_words[:5]

['เมื่อ', 'วัน', 'พฤหัสบดี', 'ที่', ' ']

In [19]:
all_tokens = sorted(list(set(all_words)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {s:i for i,s in enumerate(all_tokens)}

In [20]:
vocab

{' ': 0,
 '%': 1,
 '25': 2,
 '2568': 3,
 '30': 4,
 '31': 5,
 '90': 6,
 'Social': 7,
 'Truth': 8,
 'ก.ค.': 9,
 'กับ': 10,
 'การค้า': 11,
 'การบังคับใช้': 12,
 'ก่อน': 13,
 'ข้อตกลง': 14,
 'จะ': 15,
 'จาก': 16,
 'ซึ่ง': 17,
 'ตอบแทน': 18,
 'ต่อไป': 19,
 'ต่าง': 20,
 'ทรัมป์': 21,
 'ทั้งสองฝ่าย': 22,
 'ทำ': 23,
 'ที่': 24,
 'นำเข้า': 25,
 'บาง': 26,
 'ประกาศ': 27,
 'ประธานาธิบดี': 28,
 'ผ่าน': 29,
 'พฤหัสบดี': 30,
 'ภาษี': 31,
 'มาตรการ': 32,
 'รายการ': 33,
 'ร่วมกัน': 34,
 'วัน': 35,
 'ว่า': 36,
 'สหรัฐฯ': 37,
 'สินค้า': 38,
 'หาทาง': 39,
 'อัตรา': 40,
 'อีก': 41,
 'เก็บภาษี': 42,
 'เขา': 43,
 'เดิม': 44,
 'เมื่อ': 45,
 'เม็กซิโก': 46,
 'เลื่อน': 47,
 'โดนัลด์': 48,
 'โดย': 49,
 'ใช้': 50,
 'ใน': 51,
 'ในระหว่างนั้น': 52,
 'ไป': 53,
 '<|endoftext|>': 54,
 '<|unk|>': 55}

In [21]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}
    
    def encode(self, text):
        preprocessed = word_tokenize(text, engine="newmm") 
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int 
            else "<|unk|>" for item in preprocessed
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        return text

In [22]:
tokenizer = SimpleTokenizerV2(vocab)

text1 = "มากเขาจะเลื่อนการบังคับใช้มาตรการภาษี"
text2 = "ต่างตอบแทนอัตรา"

text = " <|endoftext|> ".join((text1, text2))

print(text)

มากเขาจะเลื่อนการบังคับใช้มาตรการภาษี <|endoftext|> ต่างตอบแทนอัตรา


In [23]:
tokenizer.encode(text)

[55, 43, 15, 47, 12, 32, 31, 54, 20, 18, 40]

In [24]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|> เขา จะ เลื่อน การบังคับใช้ มาตรการ ภาษี <|endoftext|> ต่าง ตอบแทน อัตรา'

Data sampling with a sliding window
We train LLMs to generate one word at a time, so we want to prepare the training data accordingly where the next word in a sequence represents the target to predict:

In [25]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

543


In [26]:
enc_sample = enc_text[50:]

In [27]:
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:      {y}")

x: [55, 55, 55, 55]
y:      [55, 55, 55, 45]


In [29]:
tokenizer.decode(x), tokenizer.decode(y)

('<|unk|> <|unk|> <|unk|> <|unk|>', '<|unk|> <|unk|> <|unk|> เมื่อ')

One by one, the prediction would look like as follows:

In [30]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

<|unk|> ----> <|unk|>
<|unk|> <|unk|> ----> <|unk|>
<|unk|> <|unk|> <|unk|> ----> <|unk|>
<|unk|> <|unk|> <|unk|> <|unk|> ----> เมื่อ


In [31]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.6.0


In [35]:
# Create dataset and dataloader that extract chunks from the input text dataset
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt)
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [55]:
def create_dataloader_v1(vocab, txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = SimpleTokenizerV2(vocab)

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
    print(dataset.input_ids[:5])  # Print first 5 input ids for debugging
    print(dataset.target_ids[:5])  # Print first 5 target ids for debugging

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [51]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [56]:
dataloader = create_dataloader_v1(
    vocab, raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

[tensor([55, 55, 55, 24]), tensor([55, 55, 24, 55]), tensor([55, 24, 55, 53]), tensor([24, 55, 53, 55]), tensor([55, 53, 55, 55])]
[tensor([55, 55, 24, 55]), tensor([55, 24, 55, 53]), tensor([24, 55, 53, 55]), tensor([55, 53, 55, 55]), tensor([53, 55, 55, 55])]


In [57]:
dataloader

In [58]:
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[55, 55, 55, 24]]), tensor([[55, 55, 24, 55]])]


In [59]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[55, 55, 24, 55]]), tensor([[55, 24, 55, 53]])]


In [49]:
# We can also create batched outputs
# Note that we increase the stride here so that we don't have overlaps between the batches, since more overlap could lead to increased overfitting
dataloader = create_dataloader_v1(vocab, raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[55, 55, 55, 24],
        [55, 53, 55, 55],
        [55, 55, 36, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 51, 55, 55]])

Targets:
 tensor([[55, 55, 24, 55],
        [53, 55, 55, 55],
        [55, 36, 55, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [51, 55, 55, 55]])


In [72]:
# Creating token embeddings
# The data is already almost ready for an LLM
# But lastly let us embed the tokens in a continuous vector representation using an embedding layer
# Usually, these embedding layers are part of the LLM itself and are updated (trained) during model training
# Suppose we have the following four input examples with input ids 2, 3, 5, and 1 (after tokenization):
input_ids = torch.tensor([2, 3, 5, 1])

In [63]:
# For the sake of simplicity, suppose we have a small vocabulary of only 6 words and we want to create embeddings of size 3:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [62]:
# This would result in a 6x3 weight matrix:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [65]:
# To convert a token with id 3 into a 3-dimensional vector, we do the following:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [67]:
# Note that the above is the 4th row in the embedding_layer weight matrix
# To embed all four input_ids values above, we do
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [73]:
vocab_size = 76
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [74]:
max_length = 4
dataloader = create_dataloader_v1(
    vocab, raw_text, batch_size=8, max_length=max_length, stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

[tensor([55, 55, 55, 24]), tensor([55, 53, 55, 55]), tensor([55, 55, 36, 55]), tensor([55, 55, 55, 55]), tensor([55, 55, 55, 55])]
[tensor([55, 55, 24, 55]), tensor([53, 55, 55, 55]), tensor([55, 36, 55, 55]), tensor([55, 55, 55, 55]), tensor([55, 55, 55, 55])]


In [75]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[55, 55, 55, 24],
        [55, 53, 55, 55],
        [55, 55, 36, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 55, 55, 55],
        [55, 51, 55, 55]])

Inputs shape:
 torch.Size([8, 4])


In [78]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)
print(token_embeddings)

torch.Size([8, 4, 256])
tensor([[[-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [ 1.0842,  1.5591, -0.5512,  ...,  1.0723, -0.2792,  0.5081]],

        [[-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [-1.1192,  0.5702, -0.4299,  ..., -0.9954,  0.1018, -1.1483],
         [-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191]],

        [[-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [-0.8289,  0.8767,  1.2278,  ...,  0.0446, -0.8904,  0.2113],
         [-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191]],

        ...,

        [[-0.1819,  0.8828,  1.4373,  ...,  1.0165,  0.6598, -0.2191],
         [-0.1819,  0.8828,  1.43

In [83]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
print(pos_embedding_layer.weight.shape)

# uncomment & execute the following line to see how the embedding layer weights look like
print(pos_embedding_layer.weight)

torch.Size([4, 256])
Parameter containing:
tensor([[-1.2656,  0.5118,  1.2998,  ...,  0.4382,  1.5726,  0.5510],
        [-2.2960, -1.3788, -1.2873,  ...,  2.1713, -0.7664,  0.1969],
        [-1.5482,  1.0006,  1.7814,  ...,  0.2665, -0.4404,  1.2006],
        [-0.1979, -0.7609,  1.0254,  ..., -0.1898, -1.0215,  0.6873]],
       requires_grad=True)


In [ ]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)

# uncomment & execute the following line to see how the embeddings look like
print(pos_embeddings)

torch.Size([4, 256])
tensor([[ 0.2316, -1.5919, -2.6264,  ..., -1.0669,  1.0505, -0.0637],
        [-1.0899,  0.0102, -1.5073,  ..., -0.2203, -0.0610,  1.1354],
        [-1.9272,  1.1925, -0.3605,  ..., -1.3476, -1.2624, -2.2434],
        [ 1.3647,  1.1420,  2.2042,  ..., -2.0222, -1.9595,  0.1530]],
       grad_fn=<EmbeddingBackward0>)


In [81]:
# Combine token embeddings and positional embeddings
# This is a common practice in LLMs to provide both the meaning of the token and its position in the sequence
# The input embeddings are the sum of token embeddings and positional embeddings
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

# uncomment & execute the following line to see how the embeddings look like
print(input_embeddings)

torch.Size([8, 4, 256])
tensor([[[ 0.0497, -0.7091, -1.1891,  ..., -0.0504,  1.7103, -0.2828],
         [-1.2718,  0.8930, -0.0700,  ...,  0.7962,  0.5988,  0.9163],
         [-2.1091,  2.0753,  1.0768,  ..., -0.3310, -0.6026, -2.4625],
         [ 2.4489,  2.7011,  1.6530,  ..., -0.9500, -2.2387,  0.6611]],

        [[ 0.0497, -0.7091, -1.1891,  ..., -0.0504,  1.7103, -0.2828],
         [-2.2090,  0.5805, -1.9372,  ..., -1.2157,  0.0408, -0.0129],
         [-2.1091,  2.0753,  1.0768,  ..., -0.3310, -0.6026, -2.4625],
         [ 1.1828,  2.0248,  3.6415,  ..., -1.0057, -1.2997, -0.0661]],

        [[ 0.0497, -0.7091, -1.1891,  ..., -0.0504,  1.7103, -0.2828],
         [-1.2718,  0.8930, -0.0700,  ...,  0.7962,  0.5988,  0.9163],
         [-2.7561,  2.0693,  0.8673,  ..., -1.3029, -2.1527, -2.0321],
         [ 1.1828,  2.0248,  3.6415,  ..., -1.0057, -1.2997, -0.0661]],

        ...,

        [[ 0.0497, -0.7091, -1.1891,  ..., -0.0504,  1.7103, -0.2828],
         [-1.2718,  0.8930, -0.07